// PROBLEM 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.





// an array of the fibonacci numbers:
var fibonacci = [];

// function to loop through numbers to a given limit
// and add the previous two numbers:
var sequence = function(limit){
  var total = 0;
  var x = 0;
  var y = 1;
  while(total < limit){
  	fibonacci.push(total);
  	total = x + y;
  	x = y;
  	y = total;
  }
return fibonacci;
};


// function to add only the even numbers of an array:
var sum_even = function(array){
  var i = 0;
  var total = 0;
  while(i < array.length){
	if(array[i] % 2 === 0){
		total = total + array[i];
	}
  i++;
  };
return total;
};

// output the answer:
console.log(sum_even(sequence(4000000)));

// ANSWER: 4,613,732
